import SwiftUI

struct TermsView: View {
    var body: some View {
        LegalPage(title: "Terms of Use", sections: [
            LegalSection(
                heading: "Not investment advice",
                text: "Bullion is an informational tool. Nothing in the app constitutes investment, financial, legal, or tax advice. All content is general in nature and does not consider your individual circumstances."
            ),
            LegalSection(
                heading: "Accuracy of data",
                text: "Market data may be delayed, incomplete, or inaccurate. We do not guarantee the timeliness, accuracy, or completeness of any data shown. Always verify with authoritative sources before making decisions."
            ),
            LegalSection(
                heading: "No trading",
                text: "Bullion is a read-only app. It does not execute trades, transmit orders, or modify your brokerage account. Brokerage linking via Plaid is used solely to display existing holdings and transactions."
            ),
            LegalSection(
                heading: "AI-generated content",
                text: "AI research summaries are generated by third-party models and may be wrong, outdated, or misleading. They should not be relied upon for investment decisions and are provided for general informational purposes only."
            ),
            LegalSection(
                heading: "Use at your own risk",
                text: "You are solely responsible for any decisions you make based on information in Bullion. The developer is not liable for any losses or damages arising from use of the app."
            ),
            LegalSection(
                heading: "Third-party services",
                text: "Use of Plaid and AI providers is subject to their respective terms and privacy policies. Bullion does not control and is not responsible for their practices."
            ),
            LegalSection(
                heading: "In-app purchases",
                text: "Bullion does not offer in-app purchases or subscriptions. All features are available without payment. Any costs you incur arise solely from your own accounts with third-party providers (for example, your AI provider's API usage fees), which are billed by those providers directly."
            ),
            LegalSection(
                heading: "Governing law",
                text: "These terms are governed by the laws of the jurisdiction in which the developer resides, without regard to conflict-of-laws principles. Any disputes shall be resolved in the courts of that jurisdiction."
            ),
            LegalSection(
                heading: "Contact",
                text: "For support or questions about these terms, contact support@bullion.app or through the App Store listing."
            ),
        ])
    }
}